### ISSUE TITLE
Scraper: The regex for find_all_phones provides false positives

### ISSUE THREAD

**Issue by jake-bickle** [jake-bickle/Arachnid#1]
find_all_phones will find "**123-123-1234**" out of "**123-123-1234**5" and  "**1234567890**" out of "**1234567890**123"

I'm sure there are other similar scenarios this will occur as well.

**Comment by TobinShields** [comment]
Re-wrote the regex for this--I tried to include international numbers, but this causes too many false positives. Currently, it works for all US-based numbers.
