### ISSUE TITLE
Unable to install Arachnid

### ISSUE THREAD

**Issue by orioncrocker** [jake-bickle/Arachnid#25]
$ pip install arachnid-spider
Collecting arachnid-spider
  Could not find a version that satisfies the requirement arachnid-spider (from versions: )
No matching distribution found for arachnid-spider

A fresh version of php7.3 and apache2 was installed shortly before attempting to download Arachnid via pip, not sure which requirements aren't being met.

**Comment by jake-bickle** [comment]
Did this occur before or after you installed python 3.7?

**Comment by orioncrocker** [comment]
Turns out it was a problem with how pip was installed on my machine. On the [pip website](https://pip.pypa.io/en/stable/installing/) it doesn't list the apt package that works with python3.
Everything works fine now!
